[profile.default]
src = "src"
out = "out"
libs = ["../node_modules"]
remappings = ["@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
network = "monad"
hardfork = "monad:MonadNine"
