import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const artifactPath = resolve(root, process.env.FOUNDRY_ARTIFACT ?? 'contracts/out/CoDropPass.sol/CoDropPass.json')
const outputPath = resolve(root, 'src/abi.ts')

let artifact
try {
  artifact = JSON.parse(await readFile(artifactPath, 'utf8'))
} catch (error) {
  const reason = error instanceof Error ? error.message : String(error)
  throw new Error(`Cannot read Foundry artifact at ${artifactPath}. Run forge build --root contracts first. ${reason}`)
}

if (!Array.isArray(artifact.abi)) throw new Error(`Foundry artifact has no ABI: ${artifactPath}`)

const output = `// Generated by scripts/export-abi.mjs from a compiled CoDropPass artifact. Do not edit by hand.\nexport const coDropPassAbi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
await writeFile(outputPath, output)
console.log(`Wrote ${outputPath}`)
